apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
        - name: sql
          image: mcr.microsoft.com/mssql/server:2017-GA-ubuntu
          resources:
            limits:
              memory: "3G"
              cpu: 500m
          ports:
          - containerPort: 1433
            protocol: TCP
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: "notch@12345"
---
apiVersion: v1
kind: Service
metadata:
  name: sql
spec:
  selector:
    app: sql
  ports:
  - name: sql
    port: 1433
    targetPort: 1433