apiVersion: v1
kind: Service
metadata:
  name: frontservice
spec:
  selector:
    app: frontservice
  ports:
  - port: 9000
    targetPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontservice
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontservice
  template:
    metadata:
      labels:
        app: frontservice
    spec:
      containers:
      - name: frontservice
        image: ameena3/front_service:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000

